---
- name: "sesion04_lab03"
    hosts: nodo_01
    tasks:
      - name: "Facts"
        debug:
          var: ansible_facts

      - name: "File"
        file:
          path: "/tmp/datos_{{ ansible_facts['hostname'] }}.txt"
          state: touch

      - name: "Net Device"
        blockinfile:
          path: "/tmp/datos_{{ ansible_facts['hostname'] }}.txt"
          block: |
          "IP = {{ ansible_facts['default_ipv4']['address'] }}
          MAC  = {{ ansible_facts['default_ipv4']['macaddress'] }}
          GATEWAY  = {{ ansible_facts['default_ipv4']['gateway'] }}
          NETMASK = {{ ansible_facts['default_ipv4']['netmask'] }}"
    
      - name: "Part"
        parted:
          device: /dev/sdb
          number: 1
          flags: [ lvm ]
          state: present

      - name: "VG"
        lvg:
          vg: vg_prueba
          pvs: /dev/sdb1
          pesize: "2000M"

      - name: "LV"
        lvol:
          vg: vg_prueba
          lv: lv_prueba
          size: "100%VG"
          resizefs: true
          force: yes
          state: present

      - name: "FS XFS"
        filesystem:
          fstype: xfs
          dev: /dev/mapper/vg_prueba-lv_prueba

      - name: "Path mount"
        file:
          path: /mnt/prueba
          mode: 0765
          recurse: yes
          state: directory

      - name: "Mount"
        mount:
          path: /mnt/prueba
          src: /dev/mapper/vg_prueba-lv_prueba
          fstype: xfs
          state: present

      - name: "Storage devices"
        blockinfile:
          path: "/tmp/datos_{{ ansible_facts['hostname'] }}.txt"
          marker_begin: "Los datos de almacenamiento del  {{ ansible_facts['hostname'] }} son:"
          block: |
          "Nombre del dispositivo = {{ item.device }}
          Punto de montaje = {{ item.mount }}
          Tipo de fs = {{ item.fstype }}
          Espacio total = {{ item.size_total }}
          Tamaño disponible = {{ item.size_available }}"
        loop: "{{ ansible_mounts }}"
...