---
- name: "Sesion 05 Lab 01"
  hosts: nodo01
  vars: 
    fichero: "/tmp/datos_hrarios_{{ ansible_facts['hostname'] }}.txt"

  tasks:
    - name: "Hora en registro"
      command: "date +%T"
      register: "Hora"

    - name: "Hora Moscu" 
      timezone:
        name: "Europe/Moscow"   
      register: "Cambio_Moscu"

    - name: "Hora Moscu"
      command: "date +%T"
      register: "Hora_Moscu"

    - name: "Resultado en {{ fichero }} "
      blockinfile:
        path: "{{ fichero }}"
        create: yes
        block: |
          La zona horaria antes del cambio {{ Cambio_Moscu.diff.before.name }} Y la hora era {{ Hora.stdout_lines[0] }}
          La zona horaria despuesdel cambio es {{ Cambio_Moscu.diff.after.name }} Y la hora era {{ Hora_Moscu.stdout_lines[0] }}
    
    - name: "Recupera"
      timezone:
        name: "{{ Cambio_Moscu.diff.before.name }}"
...               