---
- name: "Sesion05_Lab02"
  hosts: nodo02
  vars:
    archivos:
      - arch_01
      - arch_02
      - arch_03
      - arch_04
      - arch_05  
    dir_origen: "/tmp/archivos_lab02/"
    dir_destino: "/mnt/disco02/"
    archivo_comprimido: "archivos_lab02.zip"
  vars_files:
    "vars/defaults.yaml"
  tasks:
    - name: "Paqueteria"        
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - zip
        - unzip
        - gzip
        - bzip2

    - name: "Crea {{ dir_origen }}"
      file:
        path: "{{ dir_origen }}"
        state: directory

    - name: "Crea archivos en {{ dir_origen }}"
      file:
        path: "{{ dir_origen }}{{ item }}"
        state: touch
      loop: "{{ archivos }}"

    - name: "Particiona discos"
      parted:
        device: "{{ item.value['dispositivo'] }}"
        number: 1
        flags: [ lvm ]
        state: present
      loop: "{{ discos|dict2items }}"

    - name: "Crea VG"
      lvg:
        vg: "{{ item.value['volum_group'] }}"
        pvs: "{{ item.value['volumen_fisico'] }}"
        pesize: "{{ item.value['tamaño_vg'] }}"
      loop: "{{ discos|dict2items }}"

    - name: "Crea LV"
      lvol:
        vg: "{{ item.value['volum_group'] }}"
        lv: "lv_{{ item.value['volum_group'] }}"
        size: "{{ item.value['tamaño_lv'] }}"
        resizefs: true
        force: yes
        state: present
      loop: "{{ discos|dict2items }}"

    - name: "Configura FS"
      filesystem:
        fstype: "{{ item.value['formato_fs'] }}"
        dev: "/dev/mapper/{{ item.value['volum_group'] }}-lv_{{ item.value['volum_group'] }}"
      loop: "{{ discos|dict2items }}"

    - name: "Punto de montaje"
      file:
        path: "{{ item.value['punto_montaje'] }}"
        mode: 0765
        recurse: yes
        state: directory
      loop: "{{ discos|dict2items }}"

    - name: "Montaje"
      mount:
        path: "{{ item.value['punto_montaje'] }}"
        src: "/dev/mapper/{{ item.value['volum_group'] }}-lv_{{ item.value['volum_group'] }}"
        fstype: "{{ item.value['formato_fs'] }}"
        state: mounted
      loop: "{{ discos|dict2items }}"
    
    - name: "Comprime"
      archive:
        path: "{{ dir_origen }}"
        dest: "{{ dir_destino }}{{ archivo_comprimido }}"
        format: zip
...